name: colorize_text_avatar
description: Colorize Text Avatar is a package to generate avatar based on your user initials.
version: 1.0.4
homepage: https://github.com/deniscolak/colorize-text-avatar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
